<a href="https://colab.research.google.com/github/adithyaashok10/AI-ML-Intership/blob/main/nlp_day_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

df=pd.read_csv("/content/nlp_dataset.csv")

nltk.download('punk')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

[nltk_data] Error loading punk: Package 'punk' not found in index
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [7]:
df

                                                Text
0  Natural Language Processing is a fascinating f...
1  It bridges the gap between humans and machines...
2  NLP techniques are widely used in applications...
3  Machine translation and speech recognition are...
4  Despite its advancements, NLP faces challenges...
5  Continuous research and innovation are improvi...
6  The potential of NLP is vast, making it essent...

In [9]:
stop_words=set(stopwords.words('english'))
print(stop_words)
lemmatizer=WordNetLemmatizer()

def process_text(text):

  words=word_tokenize(text)

  filtered_words=[word.lower() for word in words if word.isalpha() and word.lower() not in stop_words]

  lemmatized_words=[lemmatizer.lemmatize(word.lower()) for word in filtered_words]

  return{
    'original_text':text,
    'word_token' :words,
    'filtered_words':filtered_words,
    'lemmatized_words':lemmatized_words
}
result = df['Text'].apply(process_text)

processed_df = pd.DataFrame([process_text(text) for text in df['Text']])

print(processed_df.head())

processed_file_path = '/content/nlp_dataset.csv'
processed_df.to_csv(processed_file_path, index=False)
print(f"Processed data saved to {processed_file_path}")

{'himself', 'and', 'in', 'she', "needn't", 'mightn', 'aren', 'some', "wouldn't", 'whom', 'isn', "they'd", 'them', 'why', 'same', "you're", 'to', 't', 'it', 'both', 'they', 'weren', "doesn't", 'while', 'so', 'here', 'were', 'does', "he's", 'me', "i've", 'other', "they've", 'his', "we'd", "they'll", "she's", 'or', 'against', 'her', 'below', 'doing', 'once', 'if', 'how', 'on', 'that', "won't", 'off', 'him', 'more', 'just', 'when', 'an', 'of', 'herself', 'any', 'no', 'hadn', "hadn't", 'll', 'haven', 'will', 'your', 'yours', 'd', 'most', "it's", "shan't", 'y', 're', "couldn't", "shouldn't", 'own', "should've", 'was', 'couldn', 'hasn', 'needn', 'should', 'doesn', "aren't", 'with', 'now', 'can', 'these', 'under', "it'd", 'nor', 'am', 'only', 've', 'didn', 'theirs', 'yourselves', 'but', "wasn't", 'because', "i'd", "you'll", 'down', 'are', "he'd", 'too', 'we', 'above', 'did', 'not', 'been', 'this', 'do', 's', 'at', 'such', 'where', 'having', 'then', 'before', "she'll", "that'll", 'i', 'be', 'the', 'out', 'our', 'about', 'as', "we'll", 'each', 'ourselves', 'until', "they're", 'he', 'between', 'ain', "don't", "didn't", 'has', "mustn't", 'up', 'who', 'o', "we've", 'very', 'by', 'is', 'themselves', 'had', 'what', 'won', "i'll", 'my', 'all', 'few', 'itself', "weren't", 'ours', 'ma', 'into', 'further', "you'd", 'through', 'than', 'myself', 'those', "hasn't", "it'll", 'a', 'its', "he'll", 'again', 'for', "she'd", 'shouldn', 'm', 'which', "you've", 'shan', 'hers', 'wouldn', 'yourself', 'during', "i'm", 'over', 'from', 'their', 'don', "haven't", 'being', 'wasn', "we're", 'mustn', "isn't", 'after', "mightn't", 'have', 'there', 'you'}
                                       original_text  \
0  Natural Language Processing is a fascinating f...
1  It bridges the gap between humans and machines...
2  NLP techniques are widely used in applications...
3  Machine translation and speech recognition are...
4  Despite its advancements, NLP faces challenges...

                                          word_token  \
0  [Natural, Language, Processing, is, a, fascina...
1  [It, bridges, the, gap, between, humans, and, ...
2  [NLP, techniques, are, widely, used, in, appli...
3  [Machine, translation, and, speech, recognitio...
4  [Despite, its, advancements, ,, NLP, faces, ch...

                                      filtered_words  \
0  [natural, language, processing, fascinating, f...
1  [bridges, gap, humans, machines, enabling, com...
2  [nlp, techniques, widely, used, applications, ...
3  [machine, translation, speech, recognition, co...
4  [despite, advancements, nlp, faces, challenges...

                                    lemmatized_words
0  [natural, language, processing, fascinating, f...
1  [bridge, gap, human, machine, enabling, comput...
2  [nlp, technique, widely, used, application, ch...
3  [machine, translation, speech, recognition, co...
4  [despite, advancement, nlp, face, challenge, i...
Processed data saved to /content/nlp_dataset.csv

In [10]:
df

                                                Text
0  Natural Language Processing is a fascinating f...
1  It bridges the gap between humans and machines...
2  NLP techniques are widely used in applications...
3  Machine translation and speech recognition are...
4  Despite its advancements, NLP faces challenges...
5  Continuous research and innovation are improvi...
6  The potential of NLP is vast, making it essent...

In [11]:
results=df['Text'].apply(process_text)
process_df=pd.DataFrame(results.tolist())
print(process_df.head())

                                       original_text  \
0  Natural Language Processing is a fascinating f...
1  It bridges the gap between humans and machines...
2  NLP techniques are widely used in applications...
3  Machine translation and speech recognition are...
4  Despite its advancements, NLP faces challenges...

                                          word_token  \
0  [Natural, Language, Processing, is, a, fascina...
1  [It, bridges, the, gap, between, humans, and, ...
2  [NLP, techniques, are, widely, used, in, appli...
3  [Machine, translation, and, speech, recognitio...
4  [Despite, its, advancements, ,, NLP, faces, ch...

                                      filtered_words  \
0  [natural, language, processing, fascinating, f...
1  [bridges, gap, humans, machines, enabling, com...
2  [nlp, techniques, widely, used, applications, ...
3  [machine, translation, speech, recognition, co...
4  [despite, advancements, nlp, faces, challenges...

                                    lemmatized_words
0  [natural, language, processing, fascinating, f...
1  [bridge, gap, human, machine, enabling, comput...
2  [nlp, technique, widely, used, application, ch...
3  [machine, translation, speech, recognition, co...
4  [despite, advancement, nlp, face, challenge, i...